# Generated by Django 4.1.1 on 2024-02-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotifForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgBefore', models.TextField()),
                ('imgAfter', models.TextField()),
                ('urutanLidi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MotifForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgBefore', models.TextField()),
                ('imgAfter', models.TextField()),
                ('urutanLidi', models.TextField()),
                ('jenisGenerate', models.TextField()),
                ('jmlBaris', models.TextField()),
                ('user', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
